<?
$PERM["robots.txt"]["10"]="W";
$PERM["vacancies"]["10"]="X";
$PERM["upload"]["10"]="X";
$PERM["specialists"]["10"]="X";
$PERM["services"]["10"]="X";
$PERM["search"]["10"]="X";
$PERM["reviews"]["10"]="X";
$PERM["restore"]["10"]="X";
$PERM["record-rules"]["10"]="X";
$PERM["privacy-policy"]["10"]="X";
$PERM["primary-form"]["10"]="X";
$PERM["personal"]["10"]="X";
$PERM["personal"]["2"]="D";
$PERM["patients"]["10"]="X";
$PERM["methods"]["10"]="X";
$PERM["local"]["10"]="X";
$PERM["includes"]["10"]="X";
$PERM["contacts"]["10"]="X";
$PERM["consultation"]["10"]="X";
$PERM["clinics"]["10"]="X";
$PERM["appointments"]["10"]="X";
$PERM["about"]["10"]="X";
$PERM["/"]["*"]="R";
?>