<?
$PERM["/"]["2"]="D";
$PERM["/"]["13"]="T_10";
$PERM["/"]["12"]="R";
$PERM["/"]["*"]="D";
$PERM["pub"]["5"]="T_8";
$PERM["pub"]["*"]="R";
$PERM["upload"]["5"]="T_8";
$PERM["upload"]["14"]="T_8";
$PERM["upload"]["*"]="R";
$PERM["extranet"]["12"]="T_8";
$PERM["extranet"]["16"]="T_10";
$PERM["extranet"]["15"]="T_8";
$PERM["extranet"]["14"]="T_8";
$PERM["extranet"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["bitrix"]["12"]="R";
$PERM["about"]["9"]="T_9";
$PERM["company"]["9"]="T_9";
$PERM["video"]["*"]="R";
?>