<?
$PERM["tools"]["5"]="T_8";
$PERM["tools"]["16"]="T_8";
$PERM["tools"]["14"]="T_8";
$PERM["admin"]["13"]="T_8";
$PERM["admin"]["16"]="T_8";
$PERM["admin"]["10"]="T_8";
$PERM["admin"]["9"]="T_8";
$PERM["admin"]["7"]="T_8";
$PERM["admin"]["6"]="T_8";
$PERM["admin"]["*"]="D";
$PERM["admin"]["23"]="R";
$PERM["wizards"]["*"]="D";
?>